export default function Terms() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-invert prose-gray max-w-none space-y-4 text-gray-300 text-sm leading-relaxed">
        <p><strong>Effective Date:</strong> February 2026</p>

        <h2 className="text-xl font-semibold text-white mt-6">1. Service Description</h2>
        <p>
          ResumeFlame provides AI-powered resume analysis and rewriting services.
          Users upload their resumes to receive feedback and optionally purchase
          professionally rewritten versions.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">2. Usage</h2>
        <p>
          Each user receives one free resume roast. Additional services (resume rewriting,
          ATS optimization) require payment. You must be at least 16 years old to use this service.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">3. Payments</h2>
        <p>
          Payments are processed securely through Paddle.com. All prices are in USD.
          By purchasing, you agree to Paddle&apos;s terms as our Merchant of Record.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">4. AI-Generated Content</h2>
        <p>
          Resume feedback and rewrites are generated by AI. While we strive for quality,
          results may not be perfect. We recommend reviewing and customizing all AI-generated
          content before using it professionally.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">5. Intellectual Property</h2>
        <p>
          You retain ownership of your original resume content. AI-generated rewrites
          are yours to use freely after purchase.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">6. Limitation of Liability</h2>
        <p>
          ResumeFlame is not responsible for job application outcomes. Our service provides
          suggestions and rewrites but does not guarantee employment results.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">7. Contact</h2>
        <p>
          For questions about these terms, please contact us at support@resumeflame.com.
        </p>
      </div>
    </main>
  );
}
