import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - ResumeFlame",
  description: "Terms of Service for ResumeFlame AI resume review and rewriting service. Read our terms including payment policy, no-refund policy, and dispute resolution.",
  alternates: { canonical: "https://resumeflame.com/terms" },
};

export default function Terms() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-invert prose-gray max-w-none space-y-4 text-gray-300 text-sm leading-relaxed">
        <p><strong>Effective Date:</strong> February 2026</p>
        <p>
          By accessing, browsing, or using ResumeFlame in any way, including uploading a resume
          or making a payment, you agree to be legally bound by these Terms of Service. If you
          do not agree to any part of these terms, you must not use the service.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">1. Service Description</h2>
        <p>
          ResumeFlame is an AI-powered digital service that provides automated resume analysis,
          scoring, feedback, and rewriting. The service is fully automated — no human reviews
          your resume. Results are generated by artificial intelligence and delivered digitally
          within seconds of payment. The nature of the product (AI-generated digital content)
          is clearly disclosed to you before purchase.
        </p>
        <p>
          You understand and agree that:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li>The product is AI-generated content, not human-written</li>
          <li>Results are delivered instantly and cannot be &quot;returned&quot;</li>
          <li>Quality may vary as with any AI-generated output</li>
          <li>The service does not guarantee any employment outcome</li>
        </ul>

        <h2 className="text-xl font-semibold text-white mt-6">2. Eligibility &amp; Account Responsibility</h2>
        <p>
          You must be at least 18 years old to make a purchase. By completing payment, you
          represent that you have the legal capacity to enter into a binding agreement, that
          you are the authorized holder of the payment method used, and that all information
          you provide is accurate. Unauthorized use of another person&apos;s payment method
          is strictly prohibited and may be reported to law enforcement.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">3. Payments &amp; Merchant of Record</h2>
        <p>
          All payments are processed securely by <strong>Lemon Squeezy</strong>, which acts
          as the Merchant of Record for all transactions. Lemon Squeezy handles payment
          processing, tax collection, and compliance on our behalf. All prices are in USD.
          By completing a purchase, you also agree to
          {" "}<a href="https://www.lemonsqueezy.com/terms" className="text-orange-400 underline" target="_blank" rel="noopener noreferrer">Lemon Squeezy&apos;s Terms of Service</a>.
        </p>
        <p>
          Lemon Squeezy, as Merchant of Record, is the entity that charges your payment method.
          ResumeFlame is the service provider that delivers the digital product. Both parties
          operate in compliance with applicable payment processing regulations.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">4. Product Delivery &amp; Proof of Delivery</h2>
        <p>
          Upon successful payment, the AI immediately begins processing your resume. Results
          (score, feedback, and rewritten resume) are delivered directly on the website within
          seconds. The product is considered <strong>fully delivered</strong> when the results
          are displayed on your screen.
        </p>
        <p>
          ResumeFlame maintains comprehensive server-side delivery logs including: timestamps
          of when processing began and completed, confirmation that results were generated
          and stored, and records of when results were accessed by the user. These logs serve
          as proof of delivery in the event of any dispute.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">5. Instant Digital Delivery Consent &amp; No Refund Policy</h2>
        <p>
          <strong>IMPORTANT — PLEASE READ CAREFULLY BEFORE PURCHASING:</strong>
        </p>
        <p>
          By clicking the purchase button, you:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Expressly request and consent to immediate performance of the service</li>
          <li>Acknowledge that the digital product will be delivered instantly upon payment</li>
          <li>Understand that once delivery begins, the service has been fully performed</li>
          <li>Waive any right of withdrawal, cooling-off period, or cancellation</li>
          <li>Accept that <strong>all sales are final and no refunds will be issued</strong></li>
        </ul>
        <p>
          This no-refund policy applies without exception to all scenarios including but not
          limited to: dissatisfaction with AI-generated results, subjective quality preferences,
          accidental purchases, duplicate purchases, purchasing the wrong plan, change of mind,
          inability to download or use the content, or any other reason whatsoever.
        </p>
        <p>
          This policy is in compliance with EU Consumer Rights Directive Article 16(m) regarding
          digital content delivered with prior express consent and acknowledgment of loss of
          withdrawal right, and equivalent consumer protection frameworks worldwide.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">6. Chargebacks &amp; Payment Disputes</h2>
        <p>
          Initiating a chargeback, payment reversal, or dispute with your bank or card issuer
          after the digital product has been successfully delivered constitutes a breach of
          these terms and may be considered fraudulent under applicable law.
        </p>
        <p>
          In the event of a dispute, ResumeFlame will provide Lemon Squeezy and the relevant
          financial institutions with complete delivery evidence including: server logs confirming
          successful generation and delivery of results, timestamps, IP addresses, and proof
          that the user accessed the delivered content. We respond to every dispute with full
          documentation.
        </p>
        <p>
          <strong>Before filing a dispute:</strong> If you experience a genuine technical issue
          that prevented delivery, contact us at <strong>support@resumeflame.com</strong> first.
          We will investigate and resolve legitimate delivery failures by re-delivering the
          product. Filing a fraudulent chargeback after receiving the product may result in
          your information being reported to fraud prevention databases.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">7. Disclaimer of Warranties</h2>
        <p>
          THE SERVICE AND ALL AI-GENERATED CONTENT ARE PROVIDED <strong>&quot;AS IS&quot;</strong> AND
          <strong> &quot;AS AVAILABLE&quot;</strong> WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS,
          IMPLIED, STATUTORY, OR OTHERWISE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, RESUMEFLAME
          DISCLAIMS ALL WARRANTIES INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS,
          RELIABILITY, AND NON-INFRINGEMENT.
        </p>
        <p>
          We do not warrant that: AI-generated results will be error-free or meet your
          expectations; the service will be uninterrupted or available at all times; the
          rewritten resume will result in job interviews, offers, or employment of any kind;
          or that the content will be suitable for any specific job application or industry.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">8. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, RESUMEFLAME, ITS OWNERS,
          OPERATORS, AFFILIATES, EMPLOYEES, AGENTS, AND SERVICE PROVIDERS SHALL NOT BE
          LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
          OR PUNITIVE DAMAGES OF ANY KIND ARISING FROM OR RELATED TO THE USE OR INABILITY
          TO USE THE SERVICE, THE AI-GENERATED CONTENT, OR ANY TRANSACTION, REGARDLESS OF
          THE THEORY OF LIABILITY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, WARRANTY,
          OR OTHERWISE), EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          IN NO EVENT SHALL THE TOTAL AGGREGATE LIABILITY OF RESUMEFLAME EXCEED THE AMOUNT
          ACTUALLY PAID BY YOU FOR THE SPECIFIC TRANSACTION GIVING RISE TO THE CLAIM. THIS
          LIMITATION APPLIES TO ALL CLAIMS IN THE AGGREGATE, NOT PER INCIDENT.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">9. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless ResumeFlame, its owners, operators,
          affiliates, and service providers from and against any and all claims, liabilities,
          damages, losses, costs, expenses, and fees (including reasonable legal fees) arising
          from: your use of the service; your violation of these terms; any content you upload;
          any dispute you initiate regarding payment, refunds, or AI-generated content; or any
          chargeback or payment dispute you file after receiving the delivered product.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">10. Binding Arbitration &amp; Waiver of Class Action</h2>
        <p>
          <strong>PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS.</strong>
        </p>
        <p>
          Any dispute, claim, or controversy arising out of or relating to these terms, the
          service, the AI-generated content, any payment transaction, or any aspect of your
          relationship with ResumeFlame shall be resolved exclusively through <strong>final
          and binding individual arbitration</strong>. You agree that:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li>All disputes will be resolved through arbitration, not in any court of law</li>
          <li>Arbitration will be conducted on an individual basis only</li>
          <li>You waive any right to participate in a class action, collective action, representative action, or consolidated arbitration</li>
          <li>You waive any right to a jury trial</li>
          <li>The arbitrator&apos;s decision is final, binding, and non-appealable</li>
        </ul>
        <p>
          Arbitration shall be conducted under the rules of the International Chamber of
          Commerce (ICC) or another internationally recognized arbitration body. The language
          of arbitration shall be English. The arbitrator shall have exclusive authority to
          resolve all disputes and shall apply these Terms of Service. The arbitral award may
          be entered as a judgment in any court of competent jurisdiction worldwide.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">11. Waiver of Legal Proceedings</h2>
        <p>
          To the fullest extent permitted by applicable law, you irrevocably and unconditionally
          waive any right to commence, join, or participate in any lawsuit, legal action, court
          proceeding, regulatory complaint, or governmental investigation against ResumeFlame
          in any court, tribunal, or regulatory body in any jurisdiction worldwide. This waiver
          applies to all claims of any nature, including claims related to: the service and its
          results; AI-generated content quality or accuracy; payment transactions and pricing;
          the no-refund policy; data handling and privacy; and any other aspect of your use of
          ResumeFlame.
        </p>
        <p>
          You acknowledge that this waiver is a fundamental and material term of this agreement
          and that ResumeFlame would not provide the service at the stated price without it.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">12. AI-Generated Content Acknowledgment</h2>
        <p>
          You expressly acknowledge and agree that all resume feedback, scores, roast content,
          and rewritten resumes are generated entirely by artificial intelligence. You accept
          full responsibility for reviewing, editing, and verifying all AI-generated content
          before using it in any professional context. ResumeFlame bears no responsibility for
          how you use the delivered content or any consequences resulting from its use.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">13. Intellectual Property</h2>
        <p>
          You retain full ownership of your original resume content. Upon delivery, AI-generated
          rewrites and feedback become your property to use without restriction. The ResumeFlame
          brand, website design, and service methodology remain the exclusive property of
          ResumeFlame.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">14. Data Handling &amp; Privacy</h2>
        <p>
          Uploaded resume content is processed in real-time and <strong>permanently deleted</strong> from
          our servers immediately after delivery of results. We do not retain, store, share, or
          sell your resume data after processing. Payment records are retained solely for
          accounting, tax compliance, and dispute resolution purposes as required by law.
          See our <a href="/privacy" className="text-orange-400 underline">Privacy Policy</a> for
          complete details.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">15. Governing Law &amp; Jurisdiction</h2>
        <p>
          These terms shall be governed by and construed in accordance with internationally
          recognized commercial law principles. Any disputes that are not subject to binding
          arbitration (if any) shall be subject to the exclusive jurisdiction agreed upon by
          the parties at the time of the dispute. You consent to the personal jurisdiction
          of any arbitral tribunal constituted under these terms.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">16. Severability</h2>
        <p>
          If any provision of these terms is held to be unenforceable, invalid, or illegal by
          any arbitrator or court of competent jurisdiction, that provision shall be modified
          to the minimum extent necessary to make it enforceable, or if modification is not
          possible, it shall be severed. All remaining provisions shall continue in full force
          and effect. The unenforceability of one provision does not affect the enforceability
          of any other provision.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">17. Entire Agreement</h2>
        <p>
          These Terms of Service, together with the <a href="/privacy" className="text-orange-400 underline">Privacy Policy</a> and
          {" "}<a href="/refund" className="text-orange-400 underline">Refund Policy</a>, constitute the entire agreement between you
          and ResumeFlame and supersede all prior agreements, understandings, and representations.
          No modification of these terms shall be effective unless made in writing by ResumeFlame.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">18. Acceptance</h2>
        <p>
          By uploading a resume, clicking any purchase button, completing a payment, or using
          any part of the ResumeFlame service, you confirm that you have read, understood, and
          agree to be legally bound by these Terms of Service in their entirety, including the
          no-refund policy, instant delivery consent, binding arbitration clause, waiver of
          class action rights, waiver of legal proceedings, disclaimer of warranties, limitation
          of liability, and indemnification obligations.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">19. Contact</h2>
        <p>
          For questions about these terms or technical support, contact us
          at <strong>support@resumeflame.com</strong>.
        </p>
      </div>
    </main>
  );
}
