export default function Terms() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-invert prose-gray max-w-none space-y-4 text-gray-300 text-sm leading-relaxed">
        <p><strong>Effective Date:</strong> February 2026</p>

        <h2 className="text-xl font-semibold text-white mt-6">1. Service Description</h2>
        <p>
          ResumeFlame provides AI-powered resume analysis and rewriting services.
          Users upload their resumes in PDF format to receive an AI-generated score,
          detailed feedback, and a professionally rewritten version of their resume.
          The service is fully automated and delivered digitally within seconds of payment.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">2. Eligibility</h2>
        <p>
          You must be at least 16 years old to use this service. By making a purchase,
          you confirm that you have the legal authority to enter into this agreement
          and to authorize the payment method used.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">3. Payments &amp; Merchant of Record</h2>
        <p>
          All payments are processed securely through <strong>Lemon Squeezy</strong>, which
          acts as our Merchant of Record. All prices are listed in USD. By completing a
          purchase, you also agree to Lemon Squeezy&apos;s
          {" "}<a href="https://www.lemonsqueezy.com/terms" className="text-orange-400 underline" target="_blank" rel="noopener noreferrer">Terms of Service</a>.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">4. Instant Digital Delivery &amp; No Refund Policy</h2>
        <p>
          ResumeFlame delivers a fully digital, AI-generated product. Upon successful payment,
          the service begins processing immediately and results are delivered within seconds.
          <strong> Because the digital product is generated and delivered instantly upon purchase,
          all sales are final and no refunds will be issued.</strong>
        </p>
        <p>
          By clicking the purchase button, you expressly consent to immediate delivery of the
          digital product and acknowledge that you waive any right to a cooling-off period or
          refund once processing begins. This policy applies to all plans, including Basic and Pro.
        </p>
        <p>
          Please review the pricing, features, and this policy carefully before purchasing.
          We do not issue refunds for dissatisfaction with AI-generated results, accidental
          purchases, duplicate purchases, or change of mind.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">5. Chargebacks &amp; Disputes</h2>
        <p>
          Filing a chargeback or payment dispute after receiving the digital product constitutes
          a breach of these terms. If you experience a genuine technical issue that prevents
          delivery, please contact us at <strong>support@resumeflame.com</strong> before
          initiating a dispute with your bank or payment provider. We maintain detailed delivery
          logs and will provide evidence of successful delivery in the event of any dispute.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">6. AI-Generated Content</h2>
        <p>
          Resume feedback, scores, and rewrites are generated by artificial intelligence.
          While we strive for high quality, results may vary and are not guaranteed to be
          perfect. We recommend reviewing and customizing all AI-generated content before
          using it in professional applications. The AI-generated nature of the product is
          clearly disclosed before purchase.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">7. Intellectual Property</h2>
        <p>
          You retain full ownership of your original resume content. AI-generated rewrites
          and feedback are yours to use freely and without restriction after purchase.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">8. Data Handling &amp; Privacy</h2>
        <p>
          Uploaded resume content is processed in real-time and permanently deleted from our
          servers after delivery. We do not store, share, or sell your resume data. Payment
          records are retained for accounting and dispute resolution purposes only.
          See our <a href="/privacy" className="text-orange-400 underline">Privacy Policy</a> for details.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">9. Limitation of Liability</h2>
        <p>
          ResumeFlame is not responsible for job application outcomes, interview results, or
          hiring decisions. Our service provides AI-generated suggestions and rewrites but
          does not guarantee employment results of any kind.
        </p>

        <h2 className="text-xl font-semibold text-white mt-6">10. Contact</h2>
        <p>
          For questions about these terms or technical support, please contact us
          at <strong>support@resumeflame.com</strong>.
        </p>
      </div>
    </main>
  );
}
